### ISSUE TITLE
Calculating NLL Smoother vs Filter - Is this correct operation or a bug?

### ISSUE THREAD

**Issue by adam-hartshorne** [pnkraemer/probdiffeq#477]
**I am wondering, is this on purpose or a bug?**

If you have the following sort of solver / solution setup
```
recipe = recipes.IsoTS0.from_params(num_derivatives=4)
strategy = smoothers.Smoother(recipe)
solver = solvers.CalibrationFreeSolver(strategy, output_scale_sqrtm=1.0)
sol = solution_routines.solve_fixed_grid(
    vf,
    initial_values=(initial_values,),
    grid=grid,
    solver=solver,
)
```
if we want to calculate the negative marginal log likelihood on terminal values, we can call the following function
`nll = dense_output.negative_marginal_log_likelihood_terminal_values(observation_std=1e-2, u=data, solution=sol[-1])
`
However, if we replace the strategy with 
`strategy = filters.Filter(recipe)`
it raises the following error
```
obs, (cor, _) = solution.posterior.init.condition_on_qoi_observation(
AttributeError: 'IsoStateSpaceVar' object has no attribute 'init'
```
The NMLL at the terminal can be calculated by the following call
```
marginals, _ = sol[-1].posterior.condition_on_qoi_observation(
                                  yt_flat, observation_std=OBS_STDEV)
nll =  -1 * jnp.sum(marginals.logpdf(yt_flat))
```
but should it be the case we can still call dense_output.negative_marginal_log_likelihood_terminal_values function?

**Comment by pnkraemer** [comment]
That is indeed a bug. Good catch; thanks for reporting! I'll take care of it.

**Comment by pnkraemer** [comment]
#479 takes care of this error. 

Upgrade your `probdiffeq` version in a couple of hours, and the problem should have vanished. Let me know if not. 

One side comment (which you probably already know, but anyway): if you compute terminal value likelihoods, I highly recommend using filters and not smoothers (once filter-errors are gone) so upgrading is definitely a good idea :)

**Comment by pnkraemer** [comment]
You can `pip install --upgrade probdiffeq` now to get the bugfix. (This also updates to the scan- version of Taylor mode, btw.)

**Comment by adam-hartshorne** [comment]
Brilliant. Thanks very much.
