### ISSUE TITLE
Unnecessary dependency on Diffeqzoo & Diffrax in v0.4.0

### ISSUE THREAD

**Issue by adam-hartshorne** [pnkraemer/probdiffeq#762]
With v0.4.0 and the rejigging of imports, you have now made a dependence on diffeqzoo and diffrax. 

taylor -> ode -> diffeqzoo.

`from probdiffeq import ivpsolve, ivpsolvers, stats, taylor`

**taylor.py**
`from probdiffeq.backend import control_flow, functools, itertools, ode, tree_util`

**ode.py**
```
import diffeqzoo.ivps
import diffrax
```

**Comment by pnkraemer** [comment]
> No I definitely using autodiff.taylor_mode_scan before.

I thought so :) 

The issue has been resolved, and a new release has been published. Upgrade your probdiffeq version, and you should be good to go. Thanks for reporting.
