### ISSUE TITLE
New Adaptive Solver - Making it JITable / Reverse Mode Differentiable

### ISSUE THREAD

**Issue by adam-hartshorne** [pnkraemer/probdiffeq#784]
I've noticed that the new solve_adaptive_save_every_step function is not jittable and is not reverse mode differentiable because it requires the use of a while loop. Diffrax uses a specific while loop that is provided as an undocumented internal function in Equinox. I'm wondering if this could allow for the removal of these limitations?

https://github.com/patrick-kidger/equinox/tree/d9b3ffde8903171263fa9fe303f2fdcb242f3bdc/equinox/internal/_loop

**Comment by adam-hartshorne** [comment]
Sorry, I meant the algorithm from the paper you released  a couple of days, solve_adaptive_save_at . Is this supposed to be JITable / reverse mode differentiable?

**Comment by pnkraemer** [comment]
I see; thanks for clarifying!

Yes, solve_adaptive_save_at is JIT'able (in fact, making this kind of solver JIT'able was one of the motivations for the algorithm; the paper discusses JIT-compilation and its effects). See [here](https://pnkraemer.github.io/probdiffeq/examples_solver_config/posterior_uncertainties/) for an example.

It is reverse-mode differentiable if you combine it with Equinox's while loop according to [these](https://pnkraemer.github.io/probdiffeq/examples_misc/use_equinox_bounded_while_loop/) instructions; but plug solve_and_save_at in accordingly.

**Comment by adam-hartshorne** [comment]
I forgot about the way you had allowed for drop-in replacement of the while loop. 

I will give it a try, although I have had a fair few issues with speed trying to use the equinox while loop in past year. It used to be fine, but more recent versions appear to return in very slow JIT compile and runtime. No idea if it is just I am an edge case, something changed making it more general has slowed it down, etc.

**Comment by adam-hartshorne** [comment]
Sure. I will test it when I get a moment and let you know if there are serious performance issues.
